import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Navigation'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next app ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <body>
        <Navigation /> 
        {children}
      
      </body>
    </html>
  )
}
